name: fastlygo_app
description: FastlyGo Delivery App
publish_to: 'none'
version: 14.3.0+18

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # Network
  http: ^1.1.0
  
  # Storage
  shared_preferences: ^2.2.2
  
  # UI
  intl: any
  
  # Maps & Location
  # google_maps_flutter: ^2.5.0
  # geolocator: ^9.0.2
  # geocoding: ^2.1.0
  # flutter_polyline_points: ^2.0.0
  
  # Image Picker
  # image_picker: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/logo/
